project:
  type: website
  output-dir: .

website:
  title: "Brian Mao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - conference_presentations.qmd
      - research_publications.qmd
      - mit_driverless.qmd
      - air_project.qmd

format:
  html:
    theme:
      - minty
      - brand
    linkcolor: blue
    css: styles.css
    toc: true

editor: visual

